org: lowdefy
service: lowdefy-telemetry-api
app: lowdefy-telemetry-api

frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  region: eu-west-1
  deploymentPrefix: lowdefy-telemetry-api

package:
  include:
    - dist/**

functions:
  lowdefy-telemetry-api-server:
    handler: dist/handler.handler
    name: lowdefy-telemetry-api-server-${opt:stage}
    environment:
      MONGODB_URI: ${param:MONGODB_URI}
    events:
      - httpApi: '*'

resources:
  Outputs:
    ApiUrl:
      Description: 'The API Gateway URL'
      Value:
        Fn::Join:
          - ''
          - - 'https://'
            - !Ref: ApiGatewayRestApi
            - '.execute-api.${self:provider.region}.amazonaws.com'
