name: Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: Check yarn cache integrity
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build packages
        run: yarn build
      - name: Test packages
        run: yarn test
      - name: Upload coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload coverage to codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/**/coverage/lcov.info:lcov
